Repository NewPick4U/NewPick4U, pull requests merged in 2025-04, with the labels that each got.

#5 [#3][comment] feat: 댓글 서비스 환경구성
  .gitignore
  comment/build.gradle
  comment/src/main/java/com/newpick4u/comment/CommentApplication.java
  comment/src/main/java/com/newpick4u/comment/comment/application/dto/.gitkeep
  comment/src/main/java/com/newpick4u/comment/comment/application/usecase/.gitkeep
  comment/src/main/java/com/newpick4u/comment/comment/domain/entity/.gitkeep
  comment/src/main/java/com/newpick4u/comment/comment/domain/repository/.gitkeep
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/jpa/.gitkeep
  comment/src/main/java/com/newpick4u/comment/comment/presentation/.gitkeep
  comment/src/main/java/com/newpick4u/comment/global/common/.gitkeep
  comment/src/main/java/com/newpick4u/comment/global/config/.gitkeep
  comment/src/main/java/com/newpick4u/comment/global/exception/.gitkeep
  comment/src/main/resources/application-develop.yml
  comment/src/main/resources/application-main.yml
  comment/src/main/resources/application-test.yml
  comment/src/main/resources/application.yml
  comment/src/test/java/com/newpick4u/comment/CommentApplicationTests.java
  settings.gradle
Labels: enhancement

#15 공통모듈 세팅
  common/build.gradle
  common/src/main/java/com/newpick4u/common/config/AutoConfig.java
  common/src/main/java/com/newpick4u/common/config/JpaAuditingConfig.java
  common/src/main/java/com/newpick4u/common/config/QueryDslConfig.java
  common/src/main/java/com/newpick4u/common/domain/BaseEntity.java
  common/src/main/java/com/newpick4u/common/exception/CustomException.java
  common/src/main/java/com/newpick4u/common/exception/ErrorResponse.java
  common/src/main/java/com/newpick4u/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/newpick4u/common/exception/type/ApiErrorCode.java
  common/src/main/java/com/newpick4u/common/exception/type/ErrorCode.java
  common/src/main/java/com/newpick4u/common/response/ApiResponse.java
  common/src/main/java/com/newpick4u/common/response/PageResponse.java
  common/src/main/resources/META-INF.spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: ✏ feat

#16 [#13][newsorign] feat: 원본뉴스 서비스 환경구성
  newsorigin/build.gradle
  newsorigin/src/main/java/com/newpick4u/newsorigin/NewsoriginApplication.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/common/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/exception/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/entity/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/repository/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/presentation/.gitkeep
  newsorigin/src/main/resources/application-develop.yml
  newsorigin/src/main/resources/application-main.yml
  newsorigin/src/main/resources/application-test.yml
  newsorigin/src/main/resources/application.yml
  newsorigin/src/test/java/com/newpick4u/newsorigin/NewsoriginApplicationTests.java
  settings.gradle
Labels: ✏ feat

#18 [#17][comment] feat: 댓글 기본 환경파일 업데이트
  comment/src/main/resources/application-develop.yml
Labels: ✏ feat

#21 고객사 서비스 엔티티 정의
  client/src/main/java/com/newpick4u/client/ClientApplication.java
  client/src/main/java/com/newpick4u/client/client/domain/entity/Advertisement.java
  client/src/main/java/com/newpick4u/client/client/domain/entity/Client.java
  client/src/main/java/com/newpick4u/client/client/domain/entity/Survey.java
  client/src/main/resources/application-develop.yml
Labels: ✏ feat

#23 jpa auditing aware 설정
  common/src/main/java/com/newpick4u/common/domain/AuditorAwareImpl.java
  common/src/main/java/com/newpick4u/common/resolver/CurrentUserInfoResolver.java
  common/src/main/java/com/newpick4u/common/resolver/annotation/CurrentUserInfo.java
  common/src/main/java/com/newpick4u/common/resolver/dto/CurrentUserInfoDto.java
  common/src/main/java/com/newpick4u/common/resolver/dto/UserRole.java
Labels: ✏ feat

#10 [#9][tag] feat : tag 도메인 초기 세팅
  settings.gradle
  tag/build.gradle
  tag/src/main/java/com/newpick4u/tag/TagApplication.java
  tag/src/main/java/com/newpick4u/tag/application/.gitkeep
  tag/src/main/java/com/newpick4u/tag/domain/entity/Tag.java
  tag/src/main/java/com/newpick4u/tag/global/common/.gitkeep
  tag/src/main/java/com/newpick4u/tag/global/config/.gitkeep
  tag/src/main/java/com/newpick4u/tag/global/exception/.gitkeep
  tag/src/main/java/com/newpick4u/tag/infrastructure/.gitkeep
  tag/src/main/java/com/newpick4u/tag/presentation/.gitkeep
  tag/src/main/resources/application-develop.yml
  tag/src/main/resources/application-main.yml
  tag/src/main/resources/application-test.yml
  tag/src/main/resources/application.yml
Labels: 🔧 fix

#25 [#24][newsorigin] feat: 원본뉴스 수집 기능 추가
  common/settings.gradle
  common/src/main/java/com/newpick4u/common/config/QueryDslConfig.java
  newsorigin/build.gradle
  newsorigin/src/main/java/com/newpick4u/newsorigin/NewsoriginApplication.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/common/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/common/CommonUtil.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/FeignClientConfig.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/FeignNaverClientConfig.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/QuerydslConfig.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/NewsOriginSchedule.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/OriginCollectClient.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/NewNewsOriginDto.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginService.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/entity/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/entity/NewsOrigin.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/repository/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/repository/NewsOriginRepository.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/NaverFeignClient.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/OriginCollectClientImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/.gitkeep
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginJpaRepository.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryCustom.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryCustomImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryImpl.java
  newsorigin/src/main/resources/application-develop.yml
  newsorigin/src/main/resources/application-test.yml
  newsorigin/src/test/java/com/newpick4u/newsorigin/NewsoriginApplicationTests.java
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImplTest.java
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/OriginCollectClientImplTest.java
Labels: ✏ feat

#28 [#27][common] fix : 공통모듈 설정 파일 오류 수정
  common/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: 🔧 fix

#34 [client] refactor : uuid 전략 수정
  client/src/main/java/com/newpick4u/client/advertisement/domain/.gitkeep
  client/src/main/java/com/newpick4u/client/advertisement/domain/entity/Advertisement.java
  client/src/main/java/com/newpick4u/client/client/domain/.gitkeep
  client/src/main/java/com/newpick4u/client/client/domain/entity/Client.java
  client/src/main/java/com/newpick4u/client/survey/domain/.gitkeep
  client/src/main/java/com/newpick4u/client/survey/domain/entity/Survey.java
Labels: 🛠 refactor

#35 [#20][client] feat : 고객사 CUD 기능 구현
  client/build.gradle
  client/src/main/java/com/newpick4u/client/client/application/dto/request/CreateClientRequestDto.java
  client/src/main/java/com/newpick4u/client/client/application/dto/request/UpdateClientRequestDto.java
  client/src/main/java/com/newpick4u/client/client/application/exception/ClientException.java
  client/src/main/java/com/newpick4u/client/client/application/usecase/ClientService.java
  client/src/main/java/com/newpick4u/client/client/application/usecase/ClientServiceImpl.java
  client/src/main/java/com/newpick4u/client/client/domain/repository/ClientRepository.java
  client/src/main/java/com/newpick4u/client/client/infrastructure/jpa/ClientJpaRepository.java
  client/src/main/java/com/newpick4u/client/client/infrastructure/jpa/ClientRepositoryImpl.java
  client/src/main/java/com/newpick4u/client/client/presentation/ClientApiController.java
  client/src/test/java/com/newpick4u/client/client/application/usecase/ClientServiceImplTest.java
Labels: ✏ feat, 📋 test

#40 [#39][client] feat : 고객사 서비스 읽기 작업 구현
  client/src/main/java/com/newpick4u/client/client/application/dto/response/GetClientResponseDto.java
  client/src/main/java/com/newpick4u/client/client/application/usecase/ClientService.java
  client/src/main/java/com/newpick4u/client/client/application/usecase/ClientServiceImpl.java
  client/src/main/java/com/newpick4u/client/client/domain/criteria/SearchClientCriteria.java
  client/src/main/java/com/newpick4u/client/client/domain/repository/ClientRepository.java
  client/src/main/java/com/newpick4u/client/client/infrastructure/jpa/ClientRepositoryCustom.java
  client/src/main/java/com/newpick4u/client/client/infrastructure/jpa/ClientRepositoryCustomImpl.java
  client/src/main/java/com/newpick4u/client/client/infrastructure/jpa/ClientRepositoryImpl.java
  client/src/main/java/com/newpick4u/client/client/presentation/ClientApiController.java
  client/src/test/java/com/newpick4u/client/client/application/usecase/ClientServiceImplTest.java
Labels: ✏ feat, 📋 test

#43 [#42][newsorigin] feat: 원본뉴스 전송 기능 추가
  newsorigin/build.gradle
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/QuerydslConfig.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/global/config/WebClientConfig.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/GetOriginBodyClient.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/MessageClient.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/NewsOriginSchedule.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/NewNewsOriginDto.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/SendNewOriginDto.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/parser/BodyParser.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/parser/BodyParserImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginService.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/entity/NewsOrigin.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/domain/repository/NewsOriginRepository.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/GetOriginBodyClientImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/OriginCollectClientImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryCustom.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryCustomImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/jpa/NewsOriginRepositoryImpl.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/infrastructure/kafka/KafkaClient.java
  newsorigin/src/main/resources/application-develop.yml
  newsorigin/src/main/resources/application-test.yml
  newsorigin/src/main/resources/docker-compose-fordevelop.yml
  newsorigin/src/main/resources/html-sample.html
  newsorigin/src/main/resources/html-sample2.html
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/application/parser/BodyParserImplTest.java
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImplTest.java
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/infrastructure/client/GetOriginBodyClientImplTest.java
Labels: ✏ feat, 📋 test

#50 [advertisement] refactor : DTO 위치 변경
  client/src/main/java/com/newpick4u/client/advertisement/application/client/NewsClient.java
  client/src/main/java/com/newpick4u/client/advertisement/application/dto/response/GetNewsResponseDto.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/client/NewsClientImpl.java
  client/src/test/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImplTest.java
Labels: 🛠 refactor

#63 [#62] [ainews] AI 뉴스 서비스 로직 구현
  ainews/build.gradle
  ainews/src/main/java/com/newpick4u/ainews/AinewsApplication.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/AiClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/AiQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/NewsQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/TagQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/dto/NewsInfoDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/dto/NewsOriginDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/dto/ProceedAiNewsDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/dto/TagInfoDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsService.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsServiceImpl.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/domain/entity/AiNews.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/domain/entity/NewsCategory.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/domain/repository/AiNewsRepository.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/GeminiClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/GeminiFeignClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/dto/GeminiRequestDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/dto/GeminiResponseDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/jpa/AiNewsJpaRepository.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/jpa/AiNewsRepositoryCustom.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/jpa/AiNewsRepositoryCustomImpl.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/jpa/AiNewsRepositoryImpl.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaExceptionConsumer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaNormalConsumer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaAiProducer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaNewsProducer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaTagProducer.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/FeignClientConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/FeignGeminiClientConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/JacksonConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/KafkaConsumerConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/KafkaProducerConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/exception/.gitkeep
  ainews/src/main/resources/application-develop.yml
  ainews/src/main/resources/application-main.yml
  ainews/src/main/resources/application-test.yml
  ainews/src/main/resources/application.yml
  ainews/src/test/java/com/newpick4u/ainews/AinewsApplicationTests.java
  ainews/src/test/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsServiceImplTest.java
  ainews/src/test/java/com/newpick4u/ainews/ainews/infrastructure/ai/GeminiClientTest.java
  settings.gradle
Labels: ✏ feat, 📋 test

#61 [#51][advertisement] feat : 광고 포인트 지급
  client/build.gradle
  client/src/main/java/com/newpick4u/client/advertisement/application/dto/request/CreateAdvertiseRequestDto.java
  client/src/main/java/com/newpick4u/client/advertisement/application/exception/AdvertisementException.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/consumer/PointUpdateConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/consumer/RetryPointUpdateConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/producer/PointUpdateProducer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/request/PointRequestMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementService.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/domain/entity/Advertisement.java
  client/src/main/java/com/newpick4u/client/advertisement/domain/repository/AdvertisementRepository.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/client/NewsClientImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/jpa/AdvertisementJpaRepository.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/jpa/AdvertisementRepositoryImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/KafkaConfig.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointUpdateConsumerImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointUpdateMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointUpdateProducerImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/RetryPointUpdateConsumerImpl.java
  client/src/main/java/com/newpick4u/client/global/aop/DistributedLock.java
  client/src/main/java/com/newpick4u/client/global/aop/DistributedLockAop.java
  client/src/main/java/com/newpick4u/client/global/config/RedissonConfig.java
  client/src/main/resources/application-develop.yml
  client/src/test/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImplTest.java
  client/src/test/java/com/newpick4u/client/advertisement/application/usecase/PointGrantedCountUpdateTest.java
Labels: ✏ feat

#65 [#58][Thread] feature : 쓰레드 레디스 구현
  tag/src/test/java/com/newpick4u/tag/application/usecase/TagServiceImplTest.java
  tag/src/test/java/com/newpick4u/tag/domain/repository/TagRepositoryTest.java
  thread/build.gradle
  thread/src/main/java/com/newpick4u/thread/global/config/CacheConfig.java
  thread/src/main/java/com/newpick4u/thread/global/config/CommentClientFallback.java
  thread/src/main/java/com/newpick4u/thread/global/config/FeignClientConfig.java
  thread/src/main/java/com/newpick4u/thread/global/config/ScheduleConfig.java
  thread/src/main/java/com/newpick4u/thread/thread/application/dto/ThreadDetailResponseDto.java
  thread/src/main/java/com/newpick4u/thread/thread/application/dto/ThreadResponseDto.java
  thread/src/main/java/com/newpick4u/thread/thread/application/usecase/AiClient.java
  thread/src/main/java/com/newpick4u/thread/thread/application/usecase/ThreadService.java
  thread/src/main/java/com/newpick4u/thread/thread/application/usecase/ThreadServiceImpl.java
  thread/src/main/java/com/newpick4u/thread/thread/domain/entity/Thread.java
  thread/src/main/java/com/newpick4u/thread/thread/domain/entity/ThreadStatus.java
  thread/src/main/java/com/newpick4u/thread/thread/domain/repository/ThreadRepository.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/client/CommentClient.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/client/GeminiClient.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/client/dto/CommentResponse.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/jpa/ThreadJpaRepository.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/jpa/ThreadRepositoryImpl.java
  thread/src/main/java/com/newpick4u/thread/thread/presentation/controller/ThreadInternalController.java
  thread/src/main/resources/application-develop.yml
  thread/src/main/resources/application-test.yml
  thread/src/test/java/com/newpick4u/thread/thread/application/usecase/ThreadServiceImplTest.java
  thread/src/test/java/com/newpick4u/thread/thread/application/usecase/ThreadServiceIntegrationTest.java
  thread/src/test/java/com/newpick4u/thread/thread/infrastructure/client/GeminiClientTest.java
Labels: ✏ feat

#74 [advertisement] fix : 포인트 업데이트 시 데드락 발생 요인 수정
  client/src/main/java/com/newpick4u/client/advertisement/application/dto/request/CreateAdvertiseRequestDto.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/producer/PointUpdateProducer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/request/PointRequestMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/request/PointUpdateMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/domain/entity/Advertisement.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointUpdateProducerImpl.java
  client/src/test/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImplTest.java
  client/src/test/java/com/newpick4u/client/advertisement/application/usecase/PointGrantedCountUpdateTest.java
Labels: 🔧 fix

#76 [gateway] feat : 게이트웨이 세팅
  client/src/main/resources/application-develop.yml
  eureka-server/settings.gradle
  gateway/src/main/java/com/newpick4u/gateway/GatewayApplication.java
  gateway/src/main/java/com/newpick4u/gateway/global/config/WebFluxConfig.java
  gateway/src/main/java/com/newpick4u/gateway/global/exception/GatewayErrorCode.java
  gateway/src/main/java/com/newpick4u/gateway/global/filter/ExceptionHandlingFilter.java
  gateway/src/main/java/com/newpick4u/gateway/global/filter/JwtAuthenticationFilter.java
  gateway/src/main/java/com/newpick4u/gateway/global/util/TokenProvider.java
  gateway/src/main/resources/application-develop.yml
  gateway/src/main/resources/application-main.yml
  gateway/src/main/resources/application-test.yml
  gateway/src/main/resources/application.yml
  settings.gradle
  user/src/main/resources/application-develop.yml
  user/src/test/java/com/newpick4u/user/UserApplicationTests.java
Labels: ✏ feat

#82 [#79][server] feat : 유레카 서버 세팅
  eureka-server/build.gradle
  eureka-server/src/main/java/com/newpick4u/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  settings.gradle
Labels: ✏ feat

#83 [client] refactor : yml 설정 값 수정
  client/src/main/resources/application-develop.yml
  gateway/build.gradle
Labels: 🛠 refactor

#80 [#78][newsorigin] fix : 카프카 전송 메세지 양식 수정
  comment/src/main/java/com/newpick4u/comment/comment/domain/entity/Comment.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/dto/SendNewOriginDto.java
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImpl.java
  newsorigin/src/test/java/com/newpick4u/newsorigin/newsorigin/application/usecase/NewsOriginServiceImplTest.java
Labels: 🔧 fix

#85 1차 연동 테스트 수정 사항 반영
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/GeminiClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaExceptionConsumer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaNormalConsumer.java
  ainews/src/main/resources/application-develop.yml
  client/src/main/java/com/newpick4u/client/global/config/RedissonConfig.java
  client/src/main/resources/application-develop.yml
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/client/ThreadClientImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/client/dto/GetNewsResponseDto.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/client/dto/GetThreadResponseDto.java
  comment/src/main/java/com/newpick4u/comment/global/config/RedisConfig.java
  comment/src/main/resources/application-develop.yml
  comment/src/main/resources/docker-compose-fordevelop.yml
  comment/src/test/java/com/newpick4u/comment/comment/application/usecase/CommentServiceImplTest.java
  eureka-server/src/main/java/com/newpick4u/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  gateway/src/main/java/com/newpick4u/gateway/global/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application-develop.yml
  gateway/src/main/resources/application-main.yml
  gateway/src/main/resources/application-test.yml
  news/src/main/java/com/newpick4u/news/news/application/dto/response/NewsResponseDto.java
  news/src/main/java/com/newpick4u/news/news/application/usecase/NewsServiceImpl.java
  news/src/main/java/com/newpick4u/news/news/domain/entity/News.java
  news/src/main/java/com/newpick4u/news/news/infrastructure/kafka/NewsInfoConsumer.java
  news/src/main/resources/application-develop.yml
  newsorigin/src/main/java/com/newpick4u/newsorigin/newsorigin/application/NewsOriginSchedule.java
  newsorigin/src/main/resources/application-develop.yml
  tag/build.gradle
  tag/src/main/java/com/newpick4u/tag/application/dto/AiNewsDto.java
  tag/src/main/java/com/newpick4u/tag/application/dto/NewsTagDto.java
  tag/src/main/java/com/newpick4u/tag/application/usecase/TagMessageHandler.java
  tag/src/main/java/com/newpick4u/tag/application/usecase/TagService.java
  tag/src/main/java/com/newpick4u/tag/application/usecase/TagServiceImpl.java
  tag/src/main/java/com/newpick4u/tag/domain/entity/Tag.java
  tag/src/main/java/com/newpick4u/tag/infrastructure/kafka/TagConsumer.java
  tag/src/main/java/com/newpick4u/tag/infrastructure/kafka/config/KafkaConfig.java
  tag/src/main/resources/application-develop.yml
  thread/build.gradle
  thread/src/main/java/com/newpick4u/thread/global/config/CommentClientFallback.java
  thread/src/main/java/com/newpick4u/thread/thread/application/usecase/ThreadServiceImpl.java
  thread/src/main/java/com/newpick4u/thread/thread/domain/entity/Thread.java
  thread/src/main/java/com/newpick4u/thread/thread/infrastructure/client/CommentClient.java
  thread/src/main/java/com/newpick4u/thread/thread/presentation/controller/ThreadInternalController.java
  thread/src/main/resources/application-develop.yml
  thread/src/main/resources/application.yml
  user/src/main/resources/application-develop.yml
Labels: 🔧 fix, 🛠 refactor, 📋 test

#86 [gateway] feat : 예외 핸들러 정의
  eureka-server/build.gradle
  eureka-server/src/test/java/com/newpick4u/eurekaserver/EurekaServerApplicationTests.java
  gateway/src/main/java/com/newpick4u/gateway/global/config/ObjectMapperConfig.java
  gateway/src/main/java/com/newpick4u/gateway/global/exception/GatewayErrorCode.java
  gateway/src/main/java/com/newpick4u/gateway/global/filter/ExceptionHandlingFilter.java
  gateway/src/main/java/com/newpick4u/gateway/global/filter/GatewayErrorWebExceptionHandler.java
  gateway/src/main/java/com/newpick4u/gateway/global/filter/JwtAuthenticationFilter.java
Labels: 🔧 fix

#88 [#87][advertisement] fix : 광고 도메인 오류 수정
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/global/config/RedissonConfig.java
Labels: 🔧 fix

#91 [#89][advertisement] feat : 광고 포인트 지급 오류 시 보상 트랜잭션 구현
  client/src/main/java/com/newpick4u/client/advertisement/application/message/consumer/PointUpdateConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/consumer/RetryPointUpdateConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/request/PointRequestFailureMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/application/message/request/PointUpdateMessage.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementService.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/domain/entity/Advertisement.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/KafkaConfig.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointRequestConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointRequestFailureConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/RetryPointRequestConsumer.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/RetryPointRequestFailureConsumer.java
  client/src/main/resources/application-develop.yml
  user/src/main/java/com/newpick4u/user/application/dto/request/PointUpdateMessage.java
  user/src/main/java/com/newpick4u/user/application/message/producer/PointRequestFailureProducer.java
  user/src/main/java/com/newpick4u/user/application/message/request/PointRequestFailureMessage.java
  user/src/main/java/com/newpick4u/user/infrastructure/kafka/KafkaConfig.java
  user/src/main/java/com/newpick4u/user/infrastructure/kafka/PointRequestFailureProducerImpl.java
  user/src/main/java/com/newpick4u/user/infrastructure/kafka/PointUpdateConsumer.java
  user/src/main/java/com/newpick4u/user/infrastructure/kafka/RetryPointUpdateConsumer.java
  user/src/main/resources/application-develop.yml
Labels: ✏ feat

#96 [#95][ainews] refactor : AI 뉴스 이슈 개선 및 리펙토링
  ainews/src/main/java/com/newpick4u/ainews/AinewsApplication.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/AiClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/AiQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/EventPublisher.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/EventType.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/NewsQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/TagQueueClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/dto/ProceedAiNewsDto.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiExceptionEventHandleService.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsSchedule.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsServiceImpl.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/application/usecase/AiNormalEventHandleService.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/domain/entity/AiNews.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/ai/GeminiClient.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaExceptionConsumer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/consumer/KafkaNormalConsumer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaAiProducer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaNewsProducer.java
  ainews/src/main/java/com/newpick4u/ainews/ainews/infrastructure/kafka/producer/KafkaTagProducer.java
  ainews/src/main/java/com/newpick4u/ainews/global/common/CommonUtil.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/FeignGeminiClientConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/KafkaConsumerConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/config/KafkaProducerConfig.java
  ainews/src/main/java/com/newpick4u/ainews/global/exception/.gitkeep
  ainews/src/main/java/com/newpick4u/ainews/global/exception/NoRemainRequestCountException.java
  ainews/src/main/resources/application-develop.yml
  ainews/src/main/resources/application-test.yml
  ainews/src/test/java/com/newpick4u/ainews/ainews/application/usecase/AiNewsServiceImplTest.java
  ainews/src/test/resources/consumer-message/consumer-message-01.json
  ainews/src/test/resources/consumer-message/consumer-message-02.json
  ainews/src/test/resources/consumer-message/consumer-message-03.json
  ainews/src/test/resources/consumer-message/consumer-message-04.json
  ainews/src/test/resources/consumer-message/consumer-message-05.json
Labels: ✏ feat, 🔧 fix, 🛠 refactor

#97 [#94][advertisement] feat : 부하테스트 관련 설정 추가
  client/build.gradle
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointRequestConsumer.java
  client/src/main/resources/application-develop.yml
Labels: ✏ feat

#99 [#98][advertisement] feat : 옵저버 패턴 적용
  client/src/main/java/com/newpick4u/client/advertisement/application/message/producer/PointUpdateProducer.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/PointUpdateProducer.java
  client/src/main/java/com/newpick4u/client/global/exception/DomainExceptionFactory.java
Labels: ✏ feat

#103 [#102][comment] refactor : 댓글 리펙토링
  comment/src/main/java/com/newpick4u/comment/CommentApplication.java
  comment/src/main/java/com/newpick4u/comment/comment/application/AdvertisementMessageClient.java
  comment/src/main/java/com/newpick4u/comment/comment/application/CommentSchedule.java
  comment/src/main/java/com/newpick4u/comment/comment/application/CommentSearchCriteria.java
  comment/src/main/java/com/newpick4u/comment/comment/application/EventPublisher.java
  comment/src/main/java/com/newpick4u/comment/comment/application/EventType.java
  comment/src/main/java/com/newpick4u/comment/comment/application/MessagePublishService.java
  comment/src/main/java/com/newpick4u/comment/comment/application/TagCacheRepository.java
  comment/src/main/java/com/newpick4u/comment/comment/application/dto/CommentListPageDto.java
  comment/src/main/java/com/newpick4u/comment/comment/application/dto/CommentWithGoodDto.java
  comment/src/main/java/com/newpick4u/comment/comment/application/dto/GetCommentResponseDto.java
  comment/src/main/java/com/newpick4u/comment/comment/application/usecase/CommentFacadeService.java
  comment/src/main/java/com/newpick4u/comment/comment/application/usecase/CommentFacadeServiceImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/application/usecase/CommentService.java
  comment/src/main/java/com/newpick4u/comment/comment/application/usecase/CommentServiceImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/domain/criteria/CommentSearchCriteria.java
  comment/src/main/java/com/newpick4u/comment/comment/domain/entity/CommentGood.java
  comment/src/main/java/com/newpick4u/comment/comment/domain/repository/CommentRepository.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/cache/TagCacheRepositoryImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/jpa/CommentRepositoryCustom.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/jpa/CommentRepositoryCustomImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/jpa/CommentRepositoryImpl.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/jpa/QueryDslUtil.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/kafka/KafkaAdvertisementProducer.java
  comment/src/main/java/com/newpick4u/comment/comment/infrastructure/kafka/KafkaExceptionConsumer.java
  comment/src/main/java/com/newpick4u/comment/comment/presentation/CommentApiController.java
  comment/src/main/java/com/newpick4u/comment/global/common/.gitkeep
  comment/src/main/java/com/newpick4u/comment/global/common/CommonUtil.java
  comment/src/main/java/com/newpick4u/comment/global/config/KafkaConsumerConfig.java
  comment/src/main/java/com/newpick4u/comment/global/config/KafkaProducerConfig.java
  comment/src/main/resources/application-develop.yml
  comment/src/main/resources/application-test.yml
  comment/src/main/resources/docker-compose-fordevelop.yml
  comment/src/test/java/com/newpick4u/comment/CommentApplicationTests.java
  comment/src/test/java/com/newpick4u/comment/comment/application/usecase/CommentFacadeServiceImplTest.java
  comment/src/test/java/com/newpick4u/comment/comment/application/usecase/CommentServiceImplTest.java
  comment/src/test/java/com/newpick4u/comment/comment/infrastructure/cache/TagCacheRepositoryImplTest.java
Labels: ✏ feat, 🛠 refactor, 📋 test

#113 [advertisement] feat : 도커 관련 설정 추가
  client/Dockerfile
  client/build-for-docker.sh
  client/docker-compose.yml
  client/src/main/java/com/newpick4u/client/advertisement/application/client/NewsClient.java
  client/src/main/java/com/newpick4u/client/advertisement/application/dto/request/CreateAdvertiseRequestDto.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementService.java
  client/src/main/java/com/newpick4u/client/advertisement/application/usecase/AdvertisementServiceImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/client/NewsClientImpl.java
  client/src/main/java/com/newpick4u/client/advertisement/infrastructure/kafka/KafkaConfig.java
  client/src/main/java/com/newpick4u/client/advertisement/presentation/AdvertisementApiController.java
  client/src/main/java/com/newpick4u/client/global/config/JacksonConfig.java
  client/src/main/resources/application-develop.yml
  client/src/main/resources/application-main.yml
Labels: ✏ feat

#117 [#116][advertisement] refactor : 도커 컴포즈 수정
  client/docker-compose.yml
Labels: 🔧 fix
